/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CreateAccount`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LandingPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/TestLandingPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/VocabListsPage`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CreateAccount`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomePage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LandingPage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LoginPage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/TestLandingPage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/VocabListsPage`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/CreateAccount${`?${string}` | `#${string}` | ''}` | `/screens/HomePage${`?${string}` | `#${string}` | ''}` | `/screens/LandingPage${`?${string}` | `#${string}` | ''}` | `/screens/LoginPage${`?${string}` | `#${string}` | ''}` | `/screens/TestLandingPage${`?${string}` | `#${string}` | ''}` | `/screens/VocabListsPage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CreateAccount`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LandingPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/TestLandingPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/VocabListsPage`; params?: Router.UnknownInputParams; };
    }
  }
}
